import type {
  CreditEntry,
  Profile,
  PublicProfile,
  Review,
  SessionSummary,
  SkillTag,
  TeacherCard,
} from '@/lib/types'

/**
 * Fixtures for building the UI before the backend exists.
 *
 * Every screen should be reachable and realistic from this file alone. Deliberately
 * includes the awkward cases that break naive layouts: a teacher with no ratings, a
 * long bio, a two-line skill note, an empty state, a cancelled session, and a
 * zero credit balance.
 *
 * Delete this file at the end of the API phase — nothing in `app/` should import
 * it once real loaders exist.
 */

const skill = (
  name: string,
  slug: string,
  category: SkillTag['category'],
): SkillTag => ({ id: `skill-${slug}`, name, slug, category })

export const MOCK_SKILLS: SkillTag[] = [
  skill('Data Structures & Algorithms', 'dsa', 'PROGRAMMING'),
  skill('Video Editing', 'video-editing', 'MEDIA'),
  skill('UI/UX Design', 'ui-ux-design', 'DESIGN'),
  skill('Public Speaking', 'public-speaking', 'CAREER'),
  skill('Guitar', 'guitar', 'MUSIC'),
  skill('Spoken English', 'spoken-english', 'LANGUAGE'),
  skill('Machine Learning', 'machine-learning', 'PROGRAMMING'),
  skill('Photography', 'photography', 'MEDIA'),
]

const [DSA, VIDEO, UIUX, SPEAKING, GUITAR, ENGLISH, ML, PHOTO] = MOCK_SKILLS

export const MOCK_TEACHERS: TeacherCard[] = [
  {
    id: 'u-aditya',
    name: 'Aditya Menon',
    avatarUrl: null,
    branch: 'CSE',
    year: 3,
    bio: 'Solved ~600 problems on LeetCode. I like teaching the intuition before the code.',
    skill: DSA,
    level: 'ADVANCED',
    note: 'Best for beginners starting with arrays, recursion and complexity analysis.',
    averageRating: 4.8,
    ratingCount: 12,
    sessionsTaught: 14,
    lookingFor: [VIDEO, GUITAR],
  },
  {
    id: 'u-nithya',
    name: 'Nithya Raghavan',
    avatarUrl: null,
    branch: 'ECE',
    year: 2,
    bio: 'I edit our department fest aftermovies.',
    skill: VIDEO,
    level: 'INTERMEDIATE',
    note: 'Premiere Pro and DaVinci Resolve. Bring your own footage if you have some.',
    averageRating: 4.5,
    ratingCount: 6,
    sessionsTaught: 7,
    lookingFor: [DSA],
  },
  {
    // No ratings yet — the UI must show "New teacher", never "0.0 stars".
    id: 'u-farhan',
    name: 'Farhan Qureshi',
    avatarUrl: null,
    branch: 'MECH',
    year: 4,
    bio: null,
    skill: GUITAR,
    level: 'INTERMEDIATE',
    note: null,
    averageRating: null,
    ratingCount: 0,
    sessionsTaught: 0,
    lookingFor: [PHOTO],
  },
  {
    id: 'u-shreya',
    name: 'Shreya Balakrishnan',
    avatarUrl: null,
    branch: 'CSE',
    year: 4,
    bio: 'Design lead at the college magazine. Figma is my whole personality at this point, which my roommate finds significantly less charming than I do.',
    skill: UIUX,
    level: 'ADVANCED',
    note: 'We can review your portfolio together.',
    averageRating: 5,
    ratingCount: 9,
    sessionsTaught: 11,
    lookingFor: [DSA, ML],
  },
  {
    id: 'u-vikram',
    name: 'Vikram Iyer',
    avatarUrl: null,
    branch: 'EEE',
    year: 3,
    bio: 'Debate team. I can help you stop saying "um".',
    skill: SPEAKING,
    level: 'ADVANCED',
    note: null,
    averageRating: 4.2,
    ratingCount: 5,
    sessionsTaught: 6,
    lookingFor: [ENGLISH],
  },
  {
    id: 'u-ananya',
    name: 'Ananya Pillai',
    avatarUrl: null,
    branch: 'CSE',
    year: 4,
    bio: 'Interned on a CV team last summer.',
    skill: ML,
    level: 'INTERMEDIATE',
    note: 'Start with regression, not transformers. Trust me.',
    averageRating: 4.6,
    ratingCount: 8,
    sessionsTaught: 9,
    lookingFor: [SPEAKING],
  },
  {
    id: 'u-joel',
    name: 'Joel Thomas',
    avatarUrl: null,
    branch: 'CIVIL',
    year: 2,
    bio: 'Street photography mostly.',
    skill: PHOTO,
    level: 'BEGINNER',
    note: 'Phone cameras are fine, you do not need a DSLR.',
    averageRating: 4,
    ratingCount: 2,
    sessionsTaught: 3,
    lookingFor: [VIDEO],
  },
  {
    id: 'u-meera',
    name: 'Meera Krishnan',
    avatarUrl: null,
    branch: 'IT',
    year: 3,
    bio: null,
    skill: ENGLISH,
    level: 'ADVANCED',
    note: 'Conversation practice, 1-1, no judgement.',
    averageRating: 4.9,
    ratingCount: 15,
    sessionsTaught: 18,
    lookingFor: [UIUX],
  },
]

/** The signed-in user for UI development. */
export const MOCK_PROFILE: Profile = {
  id: 'u-me',
  name: 'Ramprasanth R',
  email: 'ramprasanth@example.edu',
  avatarUrl: null,
  branch: 'CSE',
  year: 3,
  bio: 'Full-stack dev. Currently trying to get better at design.',
  phone: '+919000000000',
  credits: 3,
  teaches: [
    { skill: DSA, level: 'INTERMEDIATE', note: 'Comfortable up to graphs and DP basics.' },
    { skill: ML, level: 'BEGINNER', note: null },
  ],
  wants: [{ skill: UIUX }, { skill: VIDEO }, { skill: SPEAKING }],
  averageRating: 4.7,
  ratingCount: 7,
  sessionsTaught: 8,
  sessionsLearned: 5,
  joinedAt: new Date('2026-06-14T09:00:00Z'),
}

/** A brand-new account: the empty state every screen has to survive. */
export const MOCK_EMPTY_PROFILE: Profile = {
  ...MOCK_PROFILE,
  id: 'u-new',
  name: 'New Student',
  bio: null,
  credits: 1, // the signup bonus
  teaches: [],
  wants: [],
  averageRating: null,
  ratingCount: 0,
  sessionsTaught: 0,
  sessionsLearned: 0,
  joinedAt: new Date(),
}

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r-1',
    score: 5,
    comment: 'Explained recursion in a way that finally clicked. Patient with questions.',
    createdAt: new Date('2026-08-20T14:00:00Z'),
    author: {
      id: 'u-nithya',
      name: 'Nithya Raghavan',
      avatarUrl: null,
      branch: 'ECE',
      year: 2,
    },
    skillName: 'Data Structures & Algorithms',
  },
  {
    id: 'r-2',
    score: 4,
    comment: null, // score with no comment — the card must not collapse
    createdAt: new Date('2026-08-11T10:30:00Z'),
    author: { id: 'u-joel', name: 'Joel Thomas', avatarUrl: null, branch: 'CIVIL', year: 2 },
    skillName: 'Data Structures & Algorithms',
  },
  {
    id: 'r-3',
    score: 5,
    comment: 'Showed up on time and had actually prepared examples beforehand.',
    createdAt: new Date('2026-07-29T16:15:00Z'),
    author: { id: 'u-meera', name: 'Meera Krishnan', avatarUrl: null, branch: 'IT', year: 3 },
    skillName: 'Machine Learning',
  },
]

export const MOCK_PUBLIC_PROFILE: PublicProfile = {
  id: 'u-aditya',
  name: 'Aditya Menon',
  avatarUrl: null,
  branch: 'CSE',
  year: 3,
  bio: 'Solved ~600 problems on LeetCode. I like teaching the intuition before the code.',
  teaches: [{ skill: DSA, level: 'ADVANCED', note: 'Best for beginners.' }],
  wants: [{ skill: VIDEO }, { skill: GUITAR }],
  averageRating: 4.8,
  ratingCount: 12,
  sessionsTaught: 14,
  sessionsLearned: 4,
  joinedAt: new Date('2026-02-02T09:00:00Z'),
  recentReviews: MOCK_REVIEWS,
}

const person = (t: TeacherCard) => ({
  id: t.id,
  name: t.name,
  avatarUrl: t.avatarUrl,
  branch: t.branch,
  year: t.year,
})

/** One session in every status, so no state is left unstyled. */
export const MOCK_SESSIONS: SessionSummary[] = [
  {
    id: 's-1',
    status: 'REQUESTED',
    role: 'teacher',
    counterpart: person(MOCK_TEACHERS[1]),
    skill: DSA,
    message: 'Hey! Could you help me with dynamic programming before the placement test?',
    scheduledAt: null,
    durationMin: 60,
    mode: 'IN_PERSON',
    location: null,
    meetLink: null,
    counterpartPhone: null,
    viewerConfirmed: false,
    counterpartConfirmed: false,
    viewerRated: false,
    createdAt: new Date('2026-08-30T11:00:00Z'),
  },
  {
    id: 's-2',
    status: 'ACCEPTED',
    role: 'learner',
    counterpart: person(MOCK_TEACHERS[3]),
    skill: UIUX,
    message: 'Want to learn Figma auto-layout.',
    scheduledAt: new Date('2026-09-03T15:30:00Z'),
    durationMin: 60,
    mode: 'IN_PERSON',
    location: 'Library, 2nd floor discussion room',
    meetLink: null,
    counterpartPhone: '+919000000011',
    viewerConfirmed: false,
    counterpartConfirmed: false,
    viewerRated: false,
    createdAt: new Date('2026-08-28T09:20:00Z'),
  },
  {
    id: 's-3',
    // Waiting on the other side to confirm — the credit has NOT moved yet.
    status: 'ACCEPTED',
    role: 'teacher',
    counterpart: person(MOCK_TEACHERS[6]),
    skill: DSA,
    message: null,
    scheduledAt: new Date('2026-08-29T17:00:00Z'),
    durationMin: 90,
    mode: 'ONLINE',
    location: null,
    meetLink: 'https://meet.google.com/abc-defg-hij',
    counterpartPhone: '+919000000012',
    viewerConfirmed: true,
    counterpartConfirmed: false,
    viewerRated: false,
    createdAt: new Date('2026-08-25T12:00:00Z'),
  },
  {
    id: 's-4',
    status: 'COMPLETED',
    role: 'learner',
    counterpart: person(MOCK_TEACHERS[4]),
    skill: SPEAKING,
    message: null,
    scheduledAt: new Date('2026-08-21T13:00:00Z'),
    durationMin: 60,
    mode: 'IN_PERSON',
    location: 'Seminar hall B',
    meetLink: null,
    counterpartPhone: null,
    viewerConfirmed: true,
    counterpartConfirmed: true,
    viewerRated: false, // rating still owed — surface a prompt
    createdAt: new Date('2026-08-18T08:00:00Z'),
  },
  {
    id: 's-5',
    status: 'COMPLETED',
    role: 'teacher',
    counterpart: person(MOCK_TEACHERS[7]),
    skill: ML,
    message: null,
    scheduledAt: new Date('2026-08-14T11:00:00Z'),
    durationMin: 60,
    mode: 'ONLINE',
    location: null,
    meetLink: 'https://meet.google.com/xyz-1234-pqr',
    counterpartPhone: null,
    viewerConfirmed: true,
    counterpartConfirmed: true,
    viewerRated: true,
    createdAt: new Date('2026-08-10T10:00:00Z'),
  },
  {
    id: 's-6',
    status: 'CANCELLED',
    role: 'learner',
    counterpart: person(MOCK_TEACHERS[2]),
    skill: GUITAR,
    message: 'Complete beginner, I do own a guitar.',
    scheduledAt: new Date('2026-08-09T18:00:00Z'),
    durationMin: 60,
    mode: 'IN_PERSON',
    location: 'Music room',
    meetLink: null,
    counterpartPhone: null,
    viewerConfirmed: false,
    counterpartConfirmed: false,
    viewerRated: false,
    createdAt: new Date('2026-08-05T15:00:00Z'),
  },
  {
    id: 's-7',
    status: 'DECLINED',
    role: 'learner',
    counterpart: person(MOCK_TEACHERS[0]),
    skill: DSA,
    message: 'Can we do graphs this weekend?',
    scheduledAt: null,
    durationMin: 60,
    mode: 'ONLINE',
    location: null,
    meetLink: null,
    counterpartPhone: null,
    viewerConfirmed: false,
    counterpartConfirmed: false,
    viewerRated: false,
    createdAt: new Date('2026-08-02T19:00:00Z'),
  },
]

export const MOCK_CREDIT_HISTORY: CreditEntry[] = [
  {
    id: 'c-1',
    delta: 1,
    reason: 'SESSION_COMPLETED',
    description: 'Taught Machine Learning to Joel Thomas',
    createdAt: new Date('2026-08-14T12:00:00Z'),
  },
  {
    id: 'c-2',
    delta: -1,
    reason: 'SESSION_COMPLETED',
    description: 'Learned Public Speaking from Vikram Iyer',
    createdAt: new Date('2026-08-21T14:00:00Z'),
  },
  {
    id: 'c-3',
    delta: 1,
    reason: 'SESSION_COMPLETED',
    description: 'Taught Data Structures & Algorithms to Meera Krishnan',
    createdAt: new Date('2026-08-06T16:00:00Z'),
  },
  {
    id: 'c-4',
    delta: 1,
    reason: 'SIGNUP_BONUS',
    description: 'Welcome credit — your first session is on us',
    createdAt: new Date('2026-06-14T09:00:00Z'),
  },
]
